export const ACTION = {
    GET_TRANSCRIPTION: 'GET_TRANSCRIPTION',
    TRANSCRIPTION_RESULT: 'TRANSCRIPTION_RESULT',
    TRANSCRIPTION_ERROR: 'TRANSCRIPTION_ERROR',
    TTS: 'TTS',
    START_AUDIO_STREAM: 'START_AUDIO_STREAM',
    AUDIO_CHUNK: 'AUDIO_CHUNK',
    STREAM_COMPLETE: 'STREAM_COMPLETE',
    ERROR: 'ERROR',
};

export const TRANSCRIPT_CHECK_INTERVAL = 500; // ms
export const TRANSCRIPT_CHECK_TIMEOUT = 10000; // ms (10 seconds)